webtalk_init -webtalk_dir C:\\AT426-BU-98000-r0p1-00rel0\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-12-14 15:24:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212080266_0_0_371" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i5lprklokpspq7tf4g4brs4p57" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.392 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1607955775155" -context "sdk\\\\bsp/1607955775155"
webtalk_add_data -client sdk -key hwid -value "1607074381286" -context "sdk\\\\bsp/1607955775155"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1607955775155"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1607955775155"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1607955775155"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1607955890655"
webtalk_transmit -clientid 2653540098 -regid "212080266_0_0_371" -xml C:\\AT426-BU-98000-r0p1-00rel0\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\AT426-BU-98000-r0p1-00rel0\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\AT426-BU-98000-r0p1-00rel0\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
